### ISSUE TITLE
make would not build from first time

### ISSUE THREAD

**Issue by bander-saeed94** [udacity/CppND-System-Monitor#8]
implicit instantiation of undefined template 'std::__1::basic_istringstream<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
      std::istringstream linestream(line);

**Comment by spkadam** [comment]
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindCurses.cmake:246 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/sam/workspace_cpp/CppND-System-Monitor/build/CMakeFiles/CMakeOutput.log".
Makefile:10: recipe for target 'build' failed
make: *** [build] Error 1


Build failed! Please help.

**Comment by spkadam** [comment]
sudo apt-get install libncurses5-dev libncursesw5-dev

This solved my problem.

**Comment by SudKul** [comment]
Hi @bander-saeed94 and Participants, 
If you face issues again in the future, feel free to refer to the Knowledge hub and reach out to your assigned mentor. 
A few relevant threads are [one](https://knowledge.udacity.com/questions/60043, [two](https://knowledge.udacity.com/questions/87622), and  [three](https://knowledge.udacity.com/questions/53742).
Thanks
